from dotenv import load_dotenv
import os

load_dotenv()

# Загрузка URL сервера
NEWS_DATA_API_URL = os.getenv('NEWS_DATA_API_URL')
GLOBAL_NEWS_DATA_API_URL = os.getenv('GLOBAL_NEWS_DATA_API_URL')

CLASSIFIER_SERVER_API_URL = os.getenv('CLASSIFIER_SERVER_API_URL')
GLOBAL_CLASSIFIER_SERVER_API_URL = os.getenv('GLOBAL_CLASSIFIER_SERVER_API_URL')

CLASSIFIER_SERVER_API_URL_PORT = os.getenv('CLASSIFIER_SERVER_API_URL_PORT')
GLOBAL_CLASSIFIER_SERVER_API_URL_PORT = os.getenv('GLOBAL_CLASSIFIER_SERVER_API_URL_PORT')

# Определение URL API сервера
NEWS_DATA_API = GLOBAL_NEWS_DATA_API_URL if GLOBAL_NEWS_DATA_API_URL else NEWS_DATA_API_URL

NEWS_DATA_API = GLOBAL_CLASSIFIER_SERVER_API_URL if GLOBAL_CLASSIFIER_SERVER_API_URL else CLASSIFIER_SERVER_API_URL
NEWS_DATA_API = GLOBAL_CLASSIFIER_SERVER_API_URL_PORT if GLOBAL_CLASSIFIER_SERVER_API_URL_PORT else CLASSIFIER_SERVER_API_URL_PORT



