dataset_path: "data/processed/news_dataset.csv"
model_type: "BERT"
hyperparameters:
  learning_rate: 0.001
  batch_size: 32
  num_epochs: 10
  optimizer: "Adam"
  loss_function: "CrossEntropyLoss"
model_save_path: "experiments/2024-07-18/trained_model/"
logs_path: "experiments/2024-07-18/logs.md"